"""Edit the pitch model

Revision ID: 976f9d710fda
Revises: e338d4f5f914
Create Date: 2022-02-10 01:18:45.460891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976f9d710fda'
down_revision = 'e338d4f5f914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'time')
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
