"""Changes to database

Revision ID: e2f8d85b43d8
Revises: 976f9d710fda
Create Date: 2022-02-13 00:57:53.694803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f8d85b43d8'
down_revision = '976f9d710fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
