"""Remove name column from users table

Revision ID: e338d4f5f914
Revises: 3f00758ea508
Create Date: 2022-02-09 22:50:37.343643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e338d4f5f914'
down_revision = '3f00758ea508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
